version: '3'

services:

    bot:
        image: "bot"
        ports: 
            - "8000:8000"
        privileged: true
        
        volumes:
            - ./app:/app
        depends_on:
            - postgres
        restart: always
    postgres:
        image: "postgres:alpine"
        restart: always
